### PR TITLE
Decoding extension

### PR DESCRIPTION
**Pull request by lishamohan**
added decoding extension, which generates a message encrypted with a random caesar key, provides decoding options that can be refreshed, and demonstrates the correct decoding

### CODE REVIEW

**Review by mattxwang — CHANGES_REQUESTED** [review]
Hey Lisha! Thank you for making this PR 😄 

Unfortunately, this is failing a few ESLint rules, and thus our deploy preview won't work! 

Here's the relevant log (you can generate this yourself by running `npm run build`):

```
8:48:20 PM: Failed to compile.
8:48:20 PM: 
8:48:20 PM: ./src/Components/TextInput.js
8:48:20 PM:   Line 1:17:  'Component' is defined but never used  no-unused-vars
8:48:20 PM: ./src/Components/Vigenere/Vigenere.js
8:48:20 PM:   Line 2:8:     'TextInput' is defined but never used                                                                                                                                                            no-unused-vars
8:48:20 PM:   Line 4:10:    'string' is defined but never used                                                                                                                                                               no-unused-vars
8:48:20 PM:   Line 101:29:  Redundant alt attribute. Screen-readers already announce `img` tags as an image. You don’t need to use the words `image`, `photo,` or `picture` (or any specified custom words) in the alt prop  jsx-a11y/img-redundant-alt
8:48:20 PM:   Line 120:29:  Redundant alt attribute. Screen-readers already announce `img` tags as an image. You don’t need to use the words `image`, `photo,` or `picture` (or any specified custom words) in the alt prop  jsx-a11y/img-redundant-alt
8:48:20 PM: ./src/Components/Title/Closing.js
8:48:20 PM:   Line 31:21:  Redundant alt attribute. Screen-readers already announce `img` tags as an image. You don’t need to use the words `image`, `photo,` or `picture` (or any specified custom words) in the alt prop  jsx-a11y/img-redundant-alt
8:48:20 PM:   Line 47:21:  Redundant alt attribute. Screen-readers already announce `img` tags as an image. You don’t need to use the words `image`, `photo,` or `picture` (or any specified custom words) in the alt prop  jsx-a11y/img-redundant-alt
8:48:20 PM: ./src/Components/Caesar/Caesar.js
8:48:20 PM:   Line 4:8:  'CaesarButtons' is defined but never used  no-unused-vars
8:48:20 PM: ./src/Components/LetterBox.js
8:48:20 PM:   Line 5:7:  'LOWER_A' is assigned a value but never used  no-unused-vars
```

Do you mind fixing those errors first, so then we can build and deploy your work! I believe some (if not all) of these were not introduced in your PR, which then confuses me on why it's been allowed to deploy.

**Comment by lishamohan** [comment]
Sorry just noticed this, just fixed the errors! Also i'm in the middle of adding the name input section; should be finished with that soon. 
Also, those errors have been there for a while, but the React compiler (not sure if that's the correct terminology, but I'm referring to the messages that pop up after running npm start) has been listing them as warnings, so maybe a setting was changed with the deployment to not allow warnings? Just a guess though, I don't actually know how deployment works

**Comment by mattxwang** [comment]
Thank you for making the changes, and that's a great observation! One of the core differences between `npm start` and `npm build` is that the former creates a dev-build, where non-failing ESLint errors (like the ones we saw) are just warnings, while `npm build` uses a stricter ESLint config that makes *everything* an error! And yes, you can think of it as the "React compiler", it's a combination of several things (webpack, babel, etc.) but it's all part of the Create React App's build process!

Anyways, looks like things work on my end! We'll wait until you finish everything you want to accomplish in it, and then give it a review. Keep up the good work 😄

**Comment by lishamohan** [comment]
Ready for review!

**Review by krashanoff — CHANGES_REQUESTED** [review]
Hey Lisha, code is looking pretty good, though the use of exact measurements for things like spacing ([see here](src/Components/Decoding/decoding.css)) is usually a sketchy game.

For design feedback, I was just taking a look over things and now that I see it, it *is* a bit offputting just asking for the user's name straight away at the start of the lesson. Especially so since we lack any sort of introduction or context at the moment. I was chatting with @malsf21 earlier and we both think it might feel more natural to simply have it appear when the cipher decoding portion is introduced.

Aside from this, things are looking good to me. Thanks for handling the warnings in the repo as well!

**Review by krashanoff — CHANGES_REQUESTED** [review]
Yo Lisha! This is looking good, though I have a few things that might be worth considering changing before we merge.
* Really nitpicky, but "here's a couple options you can try" feels less like a hint and more like a getting started tooltip. We can just remove the mention of this being a hint and change it to a piece of information, and let the enigma machine-related one be the hint.
* The enigma machine was actually the name of the machine that would encrypt transmissions that was used by the Germans in WWII. My apologies that I didn't make that clear enough in our conversation on Slack. We should instead say something like "this is what was used to break the Enigma Machine's encryption in WWII".
* Indicating to the user what cipher combination was used to encrypt their information after it is resolved to "congrats, name!" would be good to have.
* Adding a "try again" button after completing the animation might be helpful.

**Review by mattxwang — APPROVED** [review]
Wow, I've got to say, @lishamohan this looks absolutely amazing! Huge fan of this extension, I think it works really well.

On my end, I don't see anything too suspicious 🔍 in the code, so I think this LGTM. Great work 😄

**Review by krashanoff — APPROVED** [review]
Great work Lisha! Thanks for addressing all our feedback. Everything works as expected, animations look good, and having indication of how the decoding is progressing is very helpful. Overall, a great addition to the lesson. Code looks clean, too. I (and I'm sure the rest of the team will) appreciate the code lifting to make life easier for development (like how you did in src/Components/Atbash/AtbashInput.js). This also LGTM :+1:

It would be nice if it was clear what cipher the key is being used in while decoding, but that is just a tiny textual adjustment to make in a final sweep. I'll be tracking all that should be done on a GitHub project board from here on out that I'll set up now and add cards to later tonight. In any case, great work!

I'll leave the merging to you!

**Pull request merged**
